
site_name: Open Quantum Design
site_description: Open Quantum Design - the world's first open-source quantum computer
#site_url: http://0.0.0.0:8000
repo_name: OpenQuantumDesign/midstack
repo_url: https://github.com/OpenQuantumDesign/midstack

copyright: Copyright &copy; 2024 Open Quantum Design
docs_dir: .
#site_dir: ../site
#index_page: docs/index.md

use_directory_urls: true
#use_directory_urls: false  # good for opening HTML files directly, but should be 'true' for deployment

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenQuantumDesign
      name: Open Quantum Design GitHub


nav:
- Get Started:
    - The Stack: docs/index.md
    - Installation: docs/get-started/installation.md
    - More details: docs/get-started/stack.md
- Tutorials:
  - Analog: docs/tutorials/analog.md
- Examples:
  - Analog:
    - Rabi Flopping: examples/one_qubit_rabi_flopping.ipynb
    - Bell state preparation: examples/bell_state.ipynb
    - GHZ state preparation: examples/ghz_state.ipynb
    - Ising model: examples/ising_model.ipynb
- Explanation:
  - Visitor: docs/technical/explanation/visitor.md
  - Compilation Flow: docs/technical/explanation/compilation-flow.md
  - Canonicalization Flow: docs/technical/explanation/canonicalization-flow.md
- API Reference:
  - Interfaces:
    - Data Structures: docs/technical/reference/interface-base.md
    - Math Expression: docs/technical/reference/math-interface.md
    - Digital: docs/technical/reference/digital-interface.md
    - Analog:
      - Dissipation: docs/technical/reference/dissipation-interface.md
      - Operations: docs/technical/reference/operations-interface.md
      - Operators: docs/technical/reference/operator-interface.md
    - Atomic: docs/technical/reference/atomic-interface.md
  - Backends:
    - Task: docs/technical/reference/task-backend.md
    - Qutip: docs/technical/reference/qutip-backend.md
  - Utilities: docs/technical/reference/utils.md


theme:
  name: material

  logo: docs/img/oqd-logo.png
  favicon: docs/img/oqd-logo.png

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: pink
    toggle:
      icon: material/weather-night  
      name: Switch to light mode

  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.tooltips
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - navigation.prune
  - toc.follow

plugins:
  - search:
  - same-dir:
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: True
#      enable_default_jupyter_cell_styling: false
#      enable_default_pandas_dataframe_styling: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_submodules: true
            docstring_style: "google"
            docstring_section_style: "table"
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: false
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://qutip.readthedocs.io/en/qutip-4.7.x/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4

  # for code snippets/syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

  # for notes/admonitions
  - admonition
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details

  # for flow diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js