
site_name: Open Quantum Design
site_description: Open Quantum Design - the world's first open-source quantum computer
#site_url: http://0.0.0.0:8000

nav:  
- Get Started:
  - Welcome to Open Quantum Design: index.md
  - Installation: get-started/installation.md
  - Tutorials: get-started/tutorials.md
  - How-to guides: get-started/how-to-guides.md
- Explanation:
  - Visitor: explanation/visitor.md
  - Compilation flow: explanation/compilation-flow.md
- Demos:
  - Analog:
    - Rabi flopping: demos/Rabi-flopping.md
    - TFIM: demos/TFIM.md
- API Reference:
  - Interfaces:
    - Digital: reference/digital-interface.md
    - Analog: reference/analog-interface.md
    - Atomic: reference/atomic-interface.md
    - Utilities: reference/utils.md


use_directory_urls: false  # good for opening HTML files directly, but should be 'true' for deployment

theme:
  name: material

  logo: img/oqd-logo.png
  favicon: img/oqd-logo.png

  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: pink
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode

  features:
  - search
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.tooltips
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - navigation.prune
  - toc.follow

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4

  # for code snippets/syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

  # for notes/admonitions
  - admonition
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details

  # for flow diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js