[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "quantumion"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = ["pydantic>=2.4", "h5py", "requests", "matplotlib", "rich"]

[project.optional-dependencies]
docs = [
    "pymdown-extensions",
    "mkdocstrings",
    "mkdocs-material",
    "mkdocstrings-python",
]
test = ["unittest", "unittest_prettify"]
qutip = ["qutip~=4.7.3"]
server = [
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "uvicorn[standard]>=0.23.2",
    "starlette>=0.27.0",
    "redis",
    "rq",
    "fastapi>=0.104.0",
    "sqlalchemy",
    "asyncpg",
    "python-multipart",
]
all = [
    "qutip~=4.7.3",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "uvicorn[standard]>=0.23.2",
    "starlette>=0.27.0",
    "redis",
    "rq",
    "fastapi>=0.104.0",
    "sqlalchemy",
    "asyncpg",
    "python-multipart",
]

[tool.setuptools]
packages = ["quantumion"]
