version: "3.9"

################################################################################

networks:
  internal:
    name: quantumion_internal

################################################################################

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: quantumion
    container_name: quantumion
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    networks:
      internal:
    depends_on:
     redis:
      condition: service_healthy


  redis:
    image: redis
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "_docker_healthcheck"]
      interval: 5s
      timeout: 25s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning
    expose:
      - "6379"
    networks:
      internal:
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
