version: "3.9"

################################################################################

networks:
  default:
    name: macvlan
    external: True
  internal:
    name: frost_internal

################################################################################

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: frost
    container_name: frost
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    networks:
      default:
        ipv4_address: 10.104.3.194
      internal:
    dns:
      - 10.104.0.1
    depends_on:
     redis:
      condition: service_healthy


  redis:
    image: redis:alpine3.18
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--raw", "incr", "_ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    expose:
      - "6379"
    networks:
      internal:
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
