version: "3.9"

################################################################################

networks:
  internal:
    name: quantumion_internal

################################################################################

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "_docker_healthcheck"]
      interval: 5s
      timeout: 25s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning
    expose:
      - "6379"
    networks:
      internal:
    volumes:
      - redis_volume:/data

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgresql_admin
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U postgresql_admin"]
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 25s
    expose:
      - "5432"
    networks:
      internal:
    volumes:
      - postgresql_volume:/var/lib/postgresql/data 

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: quantumion
    container_name: quantumion
    restart: always
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgresql
      POSTGRES_USER: postgresql_admin
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      JWT_SECRET_KEY: secret
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    networks:
      internal:
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

volumes:
  redis_volume:
    driver: local
  postgresql_volume:
    driver: local
