name: CI

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
#   workflow_dispatch:

# permissions:
#   contents: read

# jobs:
#   build:
#     strategy:
#       fail-fast: false
#       matrix:
#         version:
#           - "3.10"
#           - "3.11"
#           - "3.12"
#         os: [ubuntu-latest, windows-latest, macos-latest]
#         arch:
#           - x64
#     name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}

#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.version }}
#           cache: "pip"

#       - name: Install uv
#         uses: astral-sh/setup-uv@v4
#         with:
#           enable-cache: true

#       - name: Install the project
#         run: uv pip install .[test]

#       - name: Run tests
#         run: uv run pytest tests
